spring:
  profiles:
    active: local

---
spring:
  profiles: local

  datasource:
    url: jdbc:mysql://localhost:3306/LEDGER?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
