spring:
  profiles:
    active: local

---
spring:
  profiles: local

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/LEDGER
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver